# CLARIFYING MODELS DIRECTORY

In [1]:
from pathlib import Path
import shutil

LEGACY_N = Path(
    "/kaggle/working/runs/detect/runs/cardboard_compare/"
    "yolov8n/weights/best.pt"
)

MODEL_DIR = Path("/kaggle/working/amm_yolo/models")
MODEL_DIR.mkdir(parents=True, exist_ok=True)

if LEGACY_N.exists():
    destination = MODEL_DIR / "yolov8n_best.pt"
    shutil.copy2(LEGACY_N, destination)

    print("Existing YOLOv8n checkpoint rescued:", destination)
    print("Size (MB):", round(destination.stat().st_size / 1024**2, 2))
else:
    print("Legacy checkpoint not found at the expected path.")

    matches = [
        p for p in Path("/kaggle/working").rglob("best.pt")
        if "yolov8n" in p.parts and "weights" in p.parts
    ]

    for path in matches:
        print("Candidate:", path)

Legacy checkpoint not found at the expected path.

In [2]:
%pip install -q "ultralytics==8.4.184" roboflow pyyaml "pillow<13" "gym==0.25.2"

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for gym (pyproject.toml) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gymnax 0.0.8 requires gym>=0.26, but you have gym 0.25.2 which is incompatible.
Note: you may need to restart the kernel to use updated packages.

# IMPORTING DEPENDENCIES

In [3]:
import sys
import gc
import json
import shutil
import zipfile
import statistics
import importlib
import importlib.metadata as metadata

from pathlib import Path

import numpy as np
import pandas as pd
import yaml
import torch

# Compatibility workaround for checkpoint loading in some environments.
# Explicitly import the PyTorch internal module before loading .pt files.
import torch._utils

import ultralytics
from ultralytics import YOLO
from roboflow import Roboflow

from IPython.display import FileLink, display


# Stable project directories for this notebook.
WORK_DIR = Path("/kaggle/working/amm_yolo")
RUNS_DIR = WORK_DIR / "runs"
MODEL_DIR = WORK_DIR / "models"
DATASET_DIR = WORK_DIR / "dataset_cardboard_v2"

for directory in [WORK_DIR, RUNS_DIR, MODEL_DIR]:
    directory.mkdir(parents=True, exist_ok=True)


MODEL_CHECKPOINTS = {
    "yolov8n": "yolov8n.pt",
    "yolov8s": "yolov8s.pt",
    "yolov8m": "yolov8m.pt",
}

print("Python executable:", sys.executable)
print("Python version:", sys.version.split()[0])
print("PyTorch version:", torch.__version__)
print("PyTorch location:", torch.__file__)
print("Ultralytics version:", ultralytics.__version__)
print("Ultralytics location:", ultralytics.__file__)
print("torch._utils available:", hasattr(torch, "_utils"))
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

print("Working directory:", WORK_DIR)
print("Models directory:", MODEL_DIR)

Creating new Ultralytics Settings v0.0.8 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/usage/settings.
Python executable: /usr/bin/python3
Python version: 3.13.15
PyTorch version: 2.11.0+cu128
PyTorch location: /usr/local/lib/python3.13/dist-packages/torch/__init__.py
Ultralytics version: 8.4.184
Ultralytics location: /usr/local/lib/python3.13/dist-packages/ultralytics/__init__.py
torch._utils available: True
CUDA available: True
GPU: Tesla T4
Working directory: /kaggle/working/amm_yolo
Models directory: /kaggle/working/amm_yolo/models

# MODELS CHECK POINTS

In [4]:
try:
    smoke_test_model = YOLO("yolov8n.pt")
    print("Pretrained checkpoint loaded successfully.")

    del smoke_test_model
    gc.collect()

except Exception as exc:
    if "_utils" in str(exc):
        raise RuntimeError(
            "PyTorch checkpoint loading still fails. "
            "Do not start training yet. See the troubleshooting "
            "steps below for environment diagnostics."
        ) from exc
    raise

Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolov8n.pt to 'yolov8n.pt': 100% ━━━━━━━━━━━━ 6.2MB 16.7MB/s 0.4s
Pretrained checkpoint loaded successfully.

In [5]:
%pip check

bigframes 2.48.0 requires google-cloud-bigquery-storage, which is not installed.
gymnax 0.0.8 has requirement gym>=0.26, but you have gym 0.25.2.
google-colab 1.0.0 has requirement jupyter-server==2.20.0, but you have jupyter-server 2.12.5.
google-colab 1.0.0 has requirement pandas==2.2.3, but you have pandas 2.3.3.
google-colab 1.0.0 has requirement requests==2.32.4, but you have requests 2.34.2.
moviepy 1.0.3 has requirement decorator<5.0,>=4.0.2, but you have decorator 5.3.1.
Note: you may need to restart the kernel to use updated packages.

# EXTRACTING ARTIFACT ARCHIVES FOR ALL MODLES

In [6]:
# Extract a previously exported artifact archive, if attached as Kaggle input.
IMPORT_DIR = WORK_DIR / "imported_artifacts"
IMPORT_DIR.mkdir(parents=True, exist_ok=True)

for archive in Path("/kaggle/input").rglob("amm_yolo_artifacts.zip"):
    print("Found saved artifact archive:", archive)

    with zipfile.ZipFile(archive, "r") as zip_ref:
        zip_ref.extractall(IMPORT_DIR)

# Restore standardized model files from attached Kaggle inputs.
for model_name in MODEL_CHECKPOINTS:
    destination = MODEL_DIR / f"{model_name}_best.pt"

    if destination.exists():
        print(f"Already available: {destination.name}")
        continue

    direct_matches = list(
        Path("/kaggle/input").rglob(f"{model_name}_best.pt")
    )

    imported_matches = list(
        IMPORT_DIR.rglob(f"{model_name}_best.pt")
    )

    matches = direct_matches + imported_matches

    if matches:
        shutil.copy2(matches[0], destination)
        print("Restored:", model_name, "from", matches[0])

# Recover the previously trained YOLOv8n from the old run directory,
# if the current session still contains it.
legacy_candidates = [
    Path("/kaggle/working/runs/detect/runs/cardboard_compare/"
         "yolov8n/weights/best.pt"),
    Path("/kaggle/working/runs/cardboard_compare/"
         "yolov8n/weights/best.pt"),
]

for model_name in MODEL_CHECKPOINTS:
    destination = MODEL_DIR / f"{model_name}_best.pt"

    if destination.exists():
        continue

    candidates = [
        path for path in legacy_candidates
        if path.exists()
        and "yolov8n" in str(path)
    ] if model_name == "yolov8n" else []

    if not candidates:
        candidates = [
            p for p in Path("/kaggle/working").rglob("best.pt")
            if "weights" in p.parts and model_name in p.parts
        ]

    if candidates:
        source = max(candidates, key=lambda p: p.stat().st_mtime)
        shutil.copy2(source, destination)
        print(f"Recovered {model_name} from:", source)

print("\nAvailable model artifacts:")
for model_name in MODEL_CHECKPOINTS:
    path = MODEL_DIR / f"{model_name}_best.pt"
    print(model_name, "->", "Available" if path.exists() else "Not saved yet")

Available model artifacts:
yolov8n -> Not saved yet
yolov8s -> Not saved yet
yolov8m -> Not saved yet

# API KEY

In [7]:
from kaggle_secrets import UserSecretsClient

DATA_YAML = DATASET_DIR / "data.yaml"

if DATA_YAML.exists():
    print("Using the dataset already downloaded in this session.")

else:
    try:
        user_secrets = UserSecretsClient()
        api_key = user_secrets.get_secret("ROBOFLOW_API_KEY")

        if not api_key:
            raise ValueError("The Roboflow API key is empty.")

    except Exception as exc:
        raise RuntimeError(
            "Roboflow access is not configured. "
            "Check Kaggle Secrets: ROBOFLOW_API_KEY, "
            "and grant the Notebook access to it."
        ) from exc

    rf = Roboflow(api_key=api_key)

    project = (
        rf.workspace("dataset-t7hz7")
        .project("cardboard-eupc8")
    )

    dataset = project.version(2).download(
        "yolov8",
        location=str(DATASET_DIR),
    )

    DATA_YAML = Path(dataset.location) / "data.yaml"

assert DATA_YAML.exists(), f"Dataset YAML not found: {DATA_YAML}"

print("Dataset configuration:", DATA_YAML)

loading Roboflow workspace...
loading Roboflow project...

Downloading Dataset Version Zip in /kaggle/working/amm_yolo/dataset_cardboard_v2 to yolov8:: 100%|██████████| 14342/14342 [00:00<00:00, 61473.25it/s]

Extracting Dataset Version Zip to /kaggle/working/amm_yolo/dataset_cardboard_v2 in yolov8:: 100%|██████████| 1582/1582 [00:00<00:00, 11906.66it/s]

Dataset configuration: /kaggle/working/amm_yolo/dataset_cardboard_v2/data.yaml

# CHECKING FOR PATHS ERRORS

In [8]:
config_path = Path(DATA_YAML)
config = yaml.safe_load(config_path.read_text())

print("Dataset configuration:")
print(config)

print("\nClass names:", config.get("names"))
print("Number of classes:", config.get("nc"))
print("Training split:", config.get("train"))
print("Validation split:", config.get("val"))
print("Test split:", config.get("test"))

assert "train" in config, "The YAML file has no training split."
assert "val" in config, "The YAML file has no validation split."
assert "names" in config, "The YAML file has no class names."

names = config["names"]
num_classes = len(names)

print("\nConfirmed number of classes:", num_classes)

if num_classes == 1:
    print("Single-class detection dataset confirmed.")

Dataset configuration:
{'names': ['cardboard'], 'nc': 1, 'roboflow': {'license': 'CC BY 4.0', 'project': 'cardboard-eupc8', 'url': 'https://universe.roboflow.com/dataset-t7hz7/cardboard-eupc8/dataset/2', 'version': 2, 'workspace': 'dataset-t7hz7'}, 'test': '../test/images', 'train': '../train/images', 'val': '../valid/images'}

Class names: ['cardboard']
Number of classes: 1
Training split: ../train/images
Validation split: ../valid/images
Test split: ../test/images

Confirmed number of classes: 1
Single-class detection dataset confirmed.

# CHECKPOINTS UPDATE

In [9]:

from pathlib import Path
from IPython.display import display, FileLink
from ultralytics import YOLO
import shutil
import json
import zipfile
import gc
import torch

# --------------------------------------------------
# 1. Paths and training configuration
# --------------------------------------------------
WORK_DIR = Path(WORK_DIR)
RUNS_DIR = Path(RUNS_DIR)
MODEL_DIR = Path(MODEL_DIR)
DATA_YAML = Path(DATA_YAML)

WORK_DIR.mkdir(parents=True, exist_ok=True)
RUNS_DIR.mkdir(parents=True, exist_ok=True)
MODEL_DIR.mkdir(parents=True, exist_ok=True)

MODEL_CHECKPOINTS = {
    "yolov8n": "yolov8n.pt",
    "yolov8s": "yolov8s.pt",
    "yolov8m": "yolov8m.pt",
}

SAVE_PERIOD = 10
LATEST_BACKUP = WORK_DIR / "amm_yolo_recovery_latest.zip"


# --------------------------------------------------
# 2. Create ZIP backups without including old ZIPs
# --------------------------------------------------
def make_backup_zip(zip_path, current_run_dir=None):
    zip_path = Path(zip_path)
    temp_path = zip_path.with_name(zip_path.stem + "_building.zip")

    run_dirs = [RUNS_DIR / name for name in MODEL_CHECKPOINTS]
    if current_run_dir is not None:
        run_dirs.append(Path(current_run_dir))

    # Remove duplicate directories while preserving order.
    run_dirs = list(dict.fromkeys(run_dirs))

    with zipfile.ZipFile(
        temp_path, "w", compression=zipfile.ZIP_DEFLATED
    ) as zf:

        # Include all saved model weights and JSON metadata.
        for file_path in MODEL_DIR.iterdir():
            if (
                file_path.is_file()
                and file_path.suffix.lower() in {".pt", ".json"}
            ):
                zf.write(
                    file_path,
                    arcname=f"models/{file_path.name}"
                )

        # Include useful training results and configuration.
        useful_files = [
            "results.csv",
            "args.yaml",
            "results.png",
            "confusion_matrix.png",
            "PR_curve.png",
            "P_curve.png",
            "R_curve.png",
            "F1_curve.png",
        ]

        for run_dir in run_dirs:
            if not run_dir.exists():
                continue

            for filename in useful_files:
                file_path = run_dir / filename
                if file_path.is_file():
                    zf.write(
                        file_path,
                        arcname=f"runs/{run_dir.name}/{filename}"
                    )

    # Replace the previous ZIP only after the new one is complete.
    temp_path.replace(zip_path)


# --------------------------------------------------
# 3. Save recovery checkpoints during training
# --------------------------------------------------
def make_epoch_backup_callback(model_name):

    def backup_after_epoch(trainer):
        try:
            epoch_number = int(trainer.epoch) + 1

            # Create a recovery package every 10 epochs.
            # Also create one at the final epoch.
            if (
                epoch_number % SAVE_PERIOD != 0
                and epoch_number != int(trainer.epochs)
            ):
                return

            last_path = Path(trainer.last)
            best_path = Path(trainer.best)

            saved_last = MODEL_DIR / f"{model_name}_last.pt"
            saved_best = MODEL_DIR / f"{model_name}_best.pt"

            if last_path.is_file():
                shutil.copy2(last_path, saved_last)

            if best_path.is_file():
                shutil.copy2(best_path, saved_best)

            progress_info = {
                "model": model_name,
                "status": "in_progress",
                "epochs_completed": epoch_number,
                "epochs_requested": int(trainer.epochs),
                "last_checkpoint": str(saved_last),
                "best_weights": str(saved_best),
                "run_directory": str(trainer.save_dir),
            }

            info_path = MODEL_DIR / f"{model_name}_training_info.json"
            with open(info_path, "w", encoding="utf-8") as file:
                json.dump(progress_info, file, indent=2)

            current_run_dir = Path(trainer.save_dir)
            make_backup_zip(
                LATEST_BACKUP,
                current_run_dir=current_run_dir
            )

            print(
                f"\nRecovery backup updated: "
                f"{model_name}, epoch {epoch_number}"
            )
            print("Download the recovery ZIP if needed:")
            display(FileLink(str(LATEST_BACKUP)))

        except Exception as error:
            # A backup failure should not unnecessarily crash training.
            print(f"WARNING: Recovery backup failed: {error}")

    return backup_after_epoch


# --------------------------------------------------
# 4. Train, resume, or skip each model
# --------------------------------------------------
for model_name, checkpoint in MODEL_CHECKPOINTS.items():

    final_best = MODEL_DIR / f"{model_name}_best.pt"
    final_last = MODEL_DIR / f"{model_name}_last.pt"
    info_path = MODEL_DIR / f"{model_name}_training_info.json"

    run_dir = RUNS_DIR / model_name
    run_last = run_dir / "weights" / "last.pt"
    run_best = run_dir / "weights" / "best.pt"

    # Read training metadata, if available.
    info = {}
    if info_path.is_file():
        try:
            with open(info_path, "r", encoding="utf-8") as file:
                info = json.load(file)
        except (json.JSONDecodeError, OSError):
            info = {}

    # Skip a completed model, including one completed by the
    # previous version of the training cell.
    previously_completed = (
        final_best.is_file()
        and info_path.is_file()
        and info.get("status") in (None, "completed")
    )

    if previously_completed:
        if not final_last.is_file() and run_last.is_file():
            shutil.copy2(run_last, final_last)

        print(f"\nSkipping completed model: {model_name}")
        continue

    # Prefer the original run's last.pt. If the run directory is
    # unavailable, use the recovery copy if one was saved.
    recovery_last = (
        run_last if run_last.is_file()
        else final_last if final_last.is_file()
        else None
    )

    print(f"\n{'=' * 55}")
    print(f"Model: {model_name}")

    if recovery_last is not None:
        print(f"Resuming from checkpoint: {recovery_last}")
        model = YOLO(str(recovery_last))
    else:
        print("Starting a new training run.")
        model = YOLO(checkpoint)

    model.add_callback(
        "on_model_save",
        make_epoch_backup_callback(model_name)
    )

    try:
        if recovery_last is not None:
            # Resume the interrupted training, restoring its
            # saved training state instead of starting over.
            model.train(
                resume=True,
                data=str(DATA_YAML),
                save_period=SAVE_PERIOD,
            )
        else:
            model.train(
                data=str(DATA_YAML),
                epochs=100,
                imgsz=640,
                batch=8,
                patience=40,
                device=0,
                workers=2,
                seed=42,
                pretrained=True,
                project=str(RUNS_DIR),
                name=model_name,
                exist_ok=True,
                plots=True,
                save=True,
                save_period=SAVE_PERIOD,
            )

        # --------------------------------------------------
        # 5. Copy final weights AFTER this model finishes
        # --------------------------------------------------
        trainer = model.trainer
        actual_run_dir = Path(trainer.save_dir)

        best_source = Path(trainer.best)
        last_source = Path(trainer.last)

        if not best_source.is_file():
            best_source = actual_run_dir / "weights" / "best.pt"

        if not last_source.is_file():
            last_source = actual_run_dir / "weights" / "last.pt"

        if not best_source.is_file():
            raise FileNotFoundError(
                f"Final best.pt not found for {model_name}: "
                f"{best_source}"
            )

        if not last_source.is_file():
            raise FileNotFoundError(
                f"Final last.pt not found for {model_name}: "
                f"{last_source}"
            )

        shutil.copy2(best_source, final_best)
        shutil.copy2(last_source, final_last)

        # Mark the model completed only after both copies exist.
        completion_info = {
            "model": model_name,
            "status": "completed",
            "dataset_yaml": str(DATA_YAML),
            "epochs_requested": 100,
            "imgsz": 640,
            "batch": 8,
            "patience": 40,
            "best_weights": str(final_best),
            "last_checkpoint": str(final_last),
            "run_directory": str(actual_run_dir),
        }

        with open(info_path, "w", encoding="utf-8") as file:
            json.dump(completion_info, file, indent=2)

        # Create a separate backup after each model completes.
        completed_zip = (
            WORK_DIR / f"amm_yolo_backup_after_{model_name}.zip"
        )

        make_backup_zip(
            completed_zip,
            current_run_dir=actual_run_dir
        )

        print(f"\nCompleted: {model_name}")
        print(f"Best weights: {final_best}")
        print(f"Resume checkpoint: {final_last}")
        print("Download this completed-model backup:")
        display(FileLink(str(completed_zip)))

    except KeyboardInterrupt:
        print(f"\nTraining interrupted for {model_name}.")
        print("Look for the latest recovery ZIP below.")

        if LATEST_BACKUP.is_file():
            display(FileLink(str(LATEST_BACKUP)))

        raise

    finally:
        del model
        gc.collect()

        if torch.cuda.is_available():
            torch.cuda.empty_cache()

print("\nTraining stage finished.")

=======================================================
Model: yolov8n
Starting a new training run.
New https://pypi.org/project/ultralytics/8.4.194 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.4.184 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/working/amm_yolo/dataset_cardboard_v2/data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=100, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=yolov8n, nbs=64, nms=None, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=40, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/kaggle/working/amm_yolo/runs, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/amm_yolo/runs/yolov8n, save_frames=False, save_json=False, save_period=10, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=2, workspace=None
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 7.2MB/s 0.1s
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, 16, None, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 349/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: downloading yolo26n.pt for AMP checks (one-time, not used for training)...
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt to 'weights/yolo26n.pt': 100% ━━━━━━━━━━━━ 5.3MB 14.6MB/s 0.4s
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 515.3±188.9 MB/s, size: 18.2 KB)
train: Scanning /kaggle/working/amm_yolo/dataset_cardboard_v2/train/labels... 550 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 550/550 1.2Kit/s 0.5s
train: New cache created: /kaggle/working/amm_yolo/dataset_cardboard_v2/train/labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 458.5±162.4 MB/s, size: 19.6 KB)
val: Scanning /kaggle/working/amm_yolo/dataset_cardboard_v2/valid/labels... 156 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 156/156 1.2Kit/s 0.1s
val: New cache created: /kaggle/working/amm_yolo/dataset_cardboard_v2/valid/labels.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and determining best 'optimizer' and 'lr0' automatically...
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Plotting labels to /kaggle/working/amm_yolo/runs/yolov8n/labels.jpg...
Using 550 train, 156 val images for fraction=1.0 at imgsz=640
Using 2 dataloader workers
Logging results to /kaggle/working/amm_yolo/runs/yolov8n
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/100      1.05G      1.268      1.595      1.518         34        640: 100% ━━━━━━━━━━━━ 69/69 9.2it/s 7.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 7.2it/s 1.4s
                   all        156        418      0.687      0.526      0.576      0.324

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/100      1.32G      1.413      1.685      1.537         36        640: 1% ──────────── 1/69 2.1it/s 0.1s<31.8s

`get_trial_id` is meant to only be called inside a function that is executed by a Tuner or Trainer. Returning `None`.

      2/100      1.32G      1.357      1.356      1.543         59        640: 100% ━━━━━━━━━━━━ 69/69 14.1it/s 4.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.7it/s 0.9s
                   all        156        418      0.678      0.646        0.7      0.391

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/100      1.32G      1.386      1.389      1.615         25        640: 100% ━━━━━━━━━━━━ 69/69 14.3it/s 4.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.6it/s 0.9s
                   all        156        418      0.626      0.531      0.594      0.304

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/100      1.32G      1.366      1.344      1.591         36        640: 100% ━━━━━━━━━━━━ 69/69 13.9it/s 5.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.5it/s 0.9s
                   all        156        418       0.63       0.61      0.674      0.393

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/100      1.32G      1.385       1.36      1.607         26        640: 100% ━━━━━━━━━━━━ 69/69 14.7it/s 4.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.3it/s 0.9s
                   all        156        418      0.474      0.612      0.528      0.281

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/100      1.32G      1.356      1.339      1.611         14        640: 100% ━━━━━━━━━━━━ 69/69 14.9it/s 4.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.6it/s 0.9s
                   all        156        418      0.729      0.616      0.684      0.346

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/100      1.32G      1.351        1.3      1.591         30        640: 100% ━━━━━━━━━━━━ 69/69 12.0it/s 5.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.9it/s 0.8s
                   all        156        418      0.703       0.67      0.723      0.416

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/100      1.32G      1.369      1.289      1.617         28        640: 100% ━━━━━━━━━━━━ 69/69 14.3it/s 4.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.5it/s 0.9s
                   all        156        418      0.793      0.658      0.749      0.424

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/100      1.32G      1.341      1.269      1.576         37        640: 100% ━━━━━━━━━━━━ 69/69 14.1it/s 4.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.2it/s 0.9s
                   all        156        418      0.662      0.569      0.659      0.356

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/100      1.32G      1.294      1.209       1.55         24        640: 100% ━━━━━━━━━━━━ 69/69 13.5it/s 5.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.8it/s 0.9s
                   all        156        418      0.708      0.719      0.768      0.444

Recovery backup updated: yolov8n, epoch 10
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/100      1.32G      1.298      1.172      1.553         33        640: 100% ━━━━━━━━━━━━ 69/69 13.6it/s 5.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.3it/s 0.9s
                   all        156        418      0.815      0.699      0.808      0.483

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/100      1.32G      1.272      1.141      1.512         15        640: 100% ━━━━━━━━━━━━ 69/69 13.7it/s 5.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 10.5it/s 0.9s
                   all        156        418      0.804      0.647      0.746      0.449

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/100      1.32G      1.296      1.163      1.542         34        640: 100% ━━━━━━━━━━━━ 69/69 13.7it/s 5.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 10.2it/s 1.0s
                   all        156        418      0.808      0.732      0.801      0.487

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/100      1.32G      1.278      1.155      1.537         40        640: 100% ━━━━━━━━━━━━ 69/69 13.2it/s 5.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.0it/s 0.9s
                   all        156        418      0.756      0.646      0.734      0.424

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/100      1.32G      1.222      1.111      1.498         23        640: 100% ━━━━━━━━━━━━ 69/69 13.5it/s 5.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 10.6it/s 0.9s
                   all        156        418      0.839      0.713      0.816      0.512

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/100      1.32G      1.209      1.035      1.458         29        640: 100% ━━━━━━━━━━━━ 69/69 12.1it/s 5.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.3it/s 0.9s
                   all        156        418      0.782      0.755      0.817      0.499

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/100      1.32G      1.217      1.043      1.494         48        640: 100% ━━━━━━━━━━━━ 69/69 13.5it/s 5.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.0it/s 0.9s
                   all        156        418      0.845      0.729      0.807      0.502

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/100      1.32G      1.221       1.03      1.485         26        640: 100% ━━━━━━━━━━━━ 69/69 13.7it/s 5.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.3it/s 0.9s
                   all        156        418      0.761      0.722      0.798      0.486

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/100      1.32G      1.182      1.018      1.476         47        640: 100% ━━━━━━━━━━━━ 69/69 13.7it/s 5.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.5it/s 0.9s
                   all        156        418      0.688      0.581      0.653      0.398

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/100      1.32G      1.221      1.039      1.477         48        640: 100% ━━━━━━━━━━━━ 69/69 14.0it/s 4.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.2it/s 0.9s
                   all        156        418       0.82      0.766      0.832      0.518

Recovery backup updated: yolov8n, epoch 20
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/100      1.32G      1.166      1.006      1.445         23        640: 100% ━━━━━━━━━━━━ 69/69 13.6it/s 5.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.4it/s 0.9s
                   all        156        418      0.798      0.818      0.878      0.551

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/100      1.32G      1.189     0.9982      1.458         23        640: 100% ━━━━━━━━━━━━ 69/69 14.0it/s 4.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.9it/s 0.8s
                   all        156        418       0.88      0.754      0.867      0.546

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/100      1.32G      1.192     0.9637      1.448         25        640: 100% ━━━━━━━━━━━━ 69/69 14.2it/s 4.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.3it/s 0.9s
                   all        156        418      0.843      0.785      0.881      0.553

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/100      1.32G      1.137     0.9615      1.445         17        640: 100% ━━━━━━━━━━━━ 69/69 13.9it/s 5.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.6it/s 0.9s
                   all        156        418      0.845      0.731      0.857      0.556

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/100      1.32G      1.136     0.9564      1.442         31        640: 100% ━━━━━━━━━━━━ 69/69 13.8it/s 5.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.5it/s 0.9s
                   all        156        418      0.839      0.749      0.842      0.542

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/100      1.32G      1.165     0.9468      1.433         30        640: 100% ━━━━━━━━━━━━ 69/69 14.6it/s 4.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.6it/s 0.9s
                   all        156        418       0.85      0.684      0.801      0.516

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/100      1.32G      1.135     0.9189      1.415         15        640: 100% ━━━━━━━━━━━━ 69/69 13.9it/s 5.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.7it/s 0.9s
                   all        156        418      0.783      0.758      0.801      0.511

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/100      1.32G      1.142     0.9342      1.418         23        640: 100% ━━━━━━━━━━━━ 69/69 13.7it/s 5.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.7it/s 0.9s
                   all        156        418      0.795       0.78      0.854       0.54

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/100      1.32G      1.125     0.8898      1.404         19        640: 100% ━━━━━━━━━━━━ 69/69 14.4it/s 4.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.6it/s 0.9s
                   all        156        418      0.862      0.761      0.855      0.564

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/100      1.32G      1.112     0.8906      1.405         30        640: 100% ━━━━━━━━━━━━ 69/69 14.2it/s 4.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.3it/s 0.9s
                   all        156        418      0.853      0.754      0.849      0.563

Recovery backup updated: yolov8n, epoch 30
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/100      1.32G      1.111     0.8968      1.419         30        640: 100% ━━━━━━━━━━━━ 69/69 14.0it/s 4.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.8it/s 0.8s
                   all        156        418      0.802      0.761      0.835       0.54

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/100      1.32G      1.126     0.9442      1.435         24        640: 100% ━━━━━━━━━━━━ 69/69 14.4it/s 4.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.8it/s 0.8s
                   all        156        418      0.866      0.715      0.829      0.542

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     33/100      1.32G      1.125     0.8996      1.411         37        640: 100% ━━━━━━━━━━━━ 69/69 14.4it/s 4.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.6it/s 0.9s
                   all        156        418      0.839      0.734       0.83      0.542

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     34/100      1.32G      1.088      0.874      1.391         25        640: 100% ━━━━━━━━━━━━ 69/69 14.1it/s 4.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.6it/s 0.9s
                   all        156        418      0.908      0.773      0.884      0.583

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     35/100      1.32G      1.065     0.8456      1.365         43        640: 100% ━━━━━━━━━━━━ 69/69 14.3it/s 4.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 12.2it/s 0.8s
                   all        156        418      0.891      0.799      0.895       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     36/100      1.32G      1.069     0.8169      1.387         31        640: 100% ━━━━━━━━━━━━ 69/69 14.4it/s 4.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 12.0it/s 0.8s
                   all        156        418      0.841      0.784      0.858      0.563

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     37/100      1.32G      1.086     0.8283      1.361         45        640: 100% ━━━━━━━━━━━━ 69/69 14.2it/s 4.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 12.3it/s 0.8s
                   all        156        418      0.892      0.766      0.875      0.588

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     38/100      1.32G      1.087     0.8437      1.395         39        640: 100% ━━━━━━━━━━━━ 69/69 14.9it/s 4.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 12.0it/s 0.8s
                   all        156        418      0.886      0.727      0.861      0.554

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     39/100      1.32G      1.095     0.8286      1.387         23        640: 100% ━━━━━━━━━━━━ 69/69 14.5it/s 4.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.8it/s 0.9s
                   all        156        418      0.842      0.829       0.89      0.603

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     40/100      1.32G      1.041     0.8337      1.373         36        640: 100% ━━━━━━━━━━━━ 69/69 15.1it/s 4.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.7it/s 0.9s
                   all        156        418      0.895      0.779      0.869      0.585

Recovery backup updated: yolov8n, epoch 40
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     41/100      1.32G      1.031     0.8016       1.36         28        640: 100% ━━━━━━━━━━━━ 69/69 14.0it/s 4.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 12.4it/s 0.8s
                   all        156        418      0.846      0.794      0.883      0.594

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     42/100      1.32G      1.073     0.7925      1.355         27        640: 100% ━━━━━━━━━━━━ 69/69 14.5it/s 4.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.8it/s 0.9s
                   all        156        418      0.853      0.776      0.858      0.583

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     43/100      1.32G      1.027     0.7697      1.339         18        640: 100% ━━━━━━━━━━━━ 69/69 14.5it/s 4.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 12.2it/s 0.8s
                   all        156        418      0.883      0.742      0.848      0.563

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     44/100      1.32G      1.055     0.8151      1.388         34        640: 100% ━━━━━━━━━━━━ 69/69 14.5it/s 4.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 12.2it/s 0.8s
                   all        156        418      0.891      0.778      0.867      0.561

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     45/100      1.32G      1.053     0.8069      1.375         25        640: 100% ━━━━━━━━━━━━ 69/69 14.4it/s 4.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 12.1it/s 0.8s
                   all        156        418      0.853      0.809      0.873      0.584

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     46/100      1.32G      1.017     0.7602       1.34         23        640: 100% ━━━━━━━━━━━━ 69/69 14.4it/s 4.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 12.1it/s 0.8s
                   all        156        418      0.893      0.798      0.865      0.577

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     47/100      1.32G       1.02     0.7719       1.34         24        640: 100% ━━━━━━━━━━━━ 69/69 15.0it/s 4.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.6it/s 0.9s
                   all        156        418      0.875      0.804      0.881      0.586

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     48/100      1.32G      1.021     0.7488      1.339         29        640: 100% ━━━━━━━━━━━━ 69/69 14.6it/s 4.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 12.4it/s 0.8s
                   all        156        418      0.893      0.787      0.875      0.595

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     49/100      1.32G      1.034     0.7419      1.355         26        640: 100% ━━━━━━━━━━━━ 69/69 14.2it/s 4.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 12.4it/s 0.8s
                   all        156        418      0.896      0.786      0.884      0.584

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     50/100      1.32G      1.054     0.7567      1.344         36        640: 100% ━━━━━━━━━━━━ 69/69 14.7it/s 4.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 12.0it/s 0.8s
                   all        156        418      0.905      0.795      0.901      0.594

Recovery backup updated: yolov8n, epoch 50
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     51/100      1.32G      1.039     0.7653      1.355         34        640: 100% ━━━━━━━━━━━━ 69/69 14.4it/s 4.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 12.1it/s 0.8s
                   all        156        418      0.863      0.821      0.898      0.606

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     52/100      1.32G      1.013     0.7663      1.332         24        640: 100% ━━━━━━━━━━━━ 69/69 14.1it/s 4.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 12.2it/s 0.8s
                   all        156        418      0.898      0.804      0.896      0.607

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     53/100      1.32G      1.011     0.7317      1.327         37        640: 100% ━━━━━━━━━━━━ 69/69 14.4it/s 4.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.4it/s 0.9s
                   all        156        418      0.889      0.765      0.869      0.581

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     54/100      1.32G      1.012     0.7274       1.33         29        640: 100% ━━━━━━━━━━━━ 69/69 14.0it/s 4.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.7it/s 0.9s
                   all        156        418      0.851       0.78      0.858      0.561

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     55/100      1.32G     0.9731     0.7143      1.314         40        640: 100% ━━━━━━━━━━━━ 69/69 14.0it/s 4.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.2it/s 0.9s
                   all        156        418      0.897      0.789      0.872      0.582

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     56/100      1.32G          1     0.7095      1.312         30        640: 100% ━━━━━━━━━━━━ 69/69 13.8it/s 5.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.7it/s 0.9s
                   all        156        418      0.843      0.834       0.89      0.592

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     57/100      1.32G     0.9717     0.6836      1.289         24        640: 100% ━━━━━━━━━━━━ 69/69 13.4it/s 5.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.3it/s 0.9s
                   all        156        418      0.861      0.817      0.884        0.6

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     58/100      1.32G      0.986     0.7092      1.306         35        640: 100% ━━━━━━━━━━━━ 69/69 13.5it/s 5.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.3it/s 0.9s
                   all        156        418       0.86      0.806      0.874      0.582

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     59/100      1.32G     0.9616     0.6813      1.295         30        640: 100% ━━━━━━━━━━━━ 69/69 13.5it/s 5.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.2it/s 0.9s
                   all        156        418      0.883      0.825      0.902      0.606

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     60/100      1.32G     0.9661     0.6781      1.288         35        640: 100% ━━━━━━━━━━━━ 69/69 14.3it/s 4.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.6it/s 0.9s
                   all        156        418      0.895      0.817       0.89      0.592

Recovery backup updated: yolov8n, epoch 60
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     61/100      1.32G     0.9905     0.7065      1.313         17        640: 100% ━━━━━━━━━━━━ 69/69 13.7it/s 5.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.1it/s 0.9s
                   all        156        418      0.861      0.827      0.902      0.607

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     62/100      1.32G     0.9593     0.6729      1.289         28        640: 100% ━━━━━━━━━━━━ 69/69 14.2it/s 4.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.4it/s 0.9s
                   all        156        418      0.884      0.842      0.904      0.616

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     63/100      1.32G     0.9643     0.6753      1.294         22        640: 100% ━━━━━━━━━━━━ 69/69 13.7it/s 5.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.6it/s 0.9s
                   all        156        418      0.895      0.774      0.891        0.6

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     64/100      1.32G     0.9565     0.6595      1.289         27        640: 100% ━━━━━━━━━━━━ 69/69 13.6it/s 5.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.5it/s 0.9s
                   all        156        418      0.904      0.835      0.906      0.617

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     65/100      1.32G     0.9445     0.6617      1.282         22        640: 100% ━━━━━━━━━━━━ 69/69 14.0it/s 4.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.8it/s 0.9s
                   all        156        418      0.888      0.833      0.895      0.611

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     66/100      1.32G     0.9597     0.6675      1.306         40        640: 100% ━━━━━━━━━━━━ 69/69 13.8it/s 5.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.4it/s 0.9s
                   all        156        418        0.9      0.796      0.891      0.599

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     67/100      1.32G     0.9618     0.6816      1.289         38        640: 100% ━━━━━━━━━━━━ 69/69 13.8it/s 5.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.5it/s 0.9s
                   all        156        418      0.884      0.787      0.867      0.578

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     68/100      1.32G     0.9571     0.6651      1.289         34        640: 100% ━━━━━━━━━━━━ 69/69 13.9it/s 5.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.5it/s 0.9s
                   all        156        418       0.89      0.828      0.906      0.621

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     69/100      1.32G      0.954     0.6562       1.28         27        640: 100% ━━━━━━━━━━━━ 69/69 13.8it/s 5.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.7it/s 0.9s
                   all        156        418      0.863      0.842      0.908      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     70/100      1.32G     0.9586     0.6628      1.288         30        640: 100% ━━━━━━━━━━━━ 69/69 14.2it/s 4.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.7it/s 0.9s
                   all        156        418      0.901      0.804      0.896      0.615

Recovery backup updated: yolov8n, epoch 70
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     71/100      1.32G     0.9202     0.6406      1.264         44        640: 100% ━━━━━━━━━━━━ 69/69 13.7it/s 5.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.5it/s 0.9s
                   all        156        418       0.88      0.813      0.898      0.606

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     72/100      1.32G     0.9197     0.6214      1.271         33        640: 100% ━━━━━━━━━━━━ 69/69 14.0it/s 4.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.3it/s 0.9s
                   all        156        418      0.858      0.856      0.908      0.622

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     73/100      1.32G     0.9206     0.6229      1.268         34        640: 100% ━━━━━━━━━━━━ 69/69 14.1it/s 4.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.7it/s 0.9s
                   all        156        418       0.92      0.809      0.897      0.612

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     74/100      1.32G     0.9371     0.6335      1.268         35        640: 100% ━━━━━━━━━━━━ 69/69 14.0it/s 4.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.6it/s 0.9s
                   all        156        418      0.882      0.862       0.92      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     75/100      1.32G     0.9077     0.6154      1.254         32        640: 100% ━━━━━━━━━━━━ 69/69 14.8it/s 4.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 12.2it/s 0.8s
                   all        156        418      0.895      0.811      0.883      0.597

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     76/100      1.32G     0.8838     0.5822      1.239         30        640: 100% ━━━━━━━━━━━━ 69/69 14.6it/s 4.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 12.3it/s 0.8s
                   all        156        418      0.897      0.821      0.901      0.617

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     77/100      1.32G     0.9139     0.6103      1.254         25        640: 100% ━━━━━━━━━━━━ 69/69 14.5it/s 4.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.8it/s 0.9s
                   all        156        418       0.88      0.839      0.903      0.622

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     78/100      1.32G     0.8936     0.6037      1.251         40        640: 100% ━━━━━━━━━━━━ 69/69 14.3it/s 4.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 12.0it/s 0.8s
                   all        156        418      0.878      0.858      0.897      0.611

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     79/100      1.32G     0.8895     0.5844       1.25         22        640: 100% ━━━━━━━━━━━━ 69/69 14.6it/s 4.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 12.6it/s 0.8s
                   all        156        418      0.864      0.816      0.892      0.613

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     80/100      1.32G     0.8915     0.5887      1.244         34        640: 100% ━━━━━━━━━━━━ 69/69 14.3it/s 4.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 12.2it/s 0.8s
                   all        156        418      0.851      0.871      0.894      0.606

Recovery backup updated: yolov8n, epoch 80
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     81/100      1.32G     0.8807     0.6001      1.221         28        640: 100% ━━━━━━━━━━━━ 69/69 12.6it/s 5.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.8it/s 0.9s
                   all        156        418      0.898      0.825      0.904      0.614

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     82/100      1.32G     0.8712     0.5864      1.237         23        640: 100% ━━━━━━━━━━━━ 69/69 13.7it/s 5.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.0it/s 0.9s
                   all        156        418      0.854      0.851      0.893      0.597

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     83/100      1.32G     0.8684      0.588      1.241         44        640: 100% ━━━━━━━━━━━━ 69/69 13.9it/s 4.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.0it/s 0.9s
                   all        156        418      0.903      0.827      0.909      0.621

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     84/100      1.32G     0.8471     0.5683      1.219         24        640: 100% ━━━━━━━━━━━━ 69/69 13.8it/s 5.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.4it/s 0.9s
                   all        156        418      0.874      0.847      0.906      0.622

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     85/100      1.32G     0.8967     0.5887      1.251         40        640: 100% ━━━━━━━━━━━━ 69/69 13.7it/s 5.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.5it/s 0.9s
                   all        156        418        0.9      0.836      0.907       0.62

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     86/100      1.32G     0.8665      0.563       1.22         39        640: 100% ━━━━━━━━━━━━ 69/69 13.9it/s 5.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 10.5it/s 1.0s
                   all        156        418      0.904      0.836      0.908      0.625

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     87/100      1.32G     0.8753     0.5769       1.23         31        640: 100% ━━━━━━━━━━━━ 69/69 12.9it/s 5.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.5it/s 0.9s
                   all        156        418      0.928      0.842      0.912      0.617

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     88/100      1.32G     0.8595     0.5535      1.217         27        640: 100% ━━━━━━━━━━━━ 69/69 13.5it/s 5.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.1it/s 0.9s
                   all        156        418      0.906      0.855      0.912      0.625

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     89/100      1.32G     0.8432     0.5699      1.215         28        640: 100% ━━━━━━━━━━━━ 69/69 13.2it/s 5.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.4it/s 0.9s
                   all        156        418      0.885      0.859      0.911      0.622

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     90/100      1.32G     0.8465      0.564      1.208         31        640: 100% ━━━━━━━━━━━━ 69/69 13.1it/s 5.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 10.9it/s 0.9s
                   all        156        418      0.905      0.842      0.911      0.624

Recovery backup updated: yolov8n, epoch 90
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     91/100      1.32G     0.7639     0.4768      1.187         10        640: 100% ━━━━━━━━━━━━ 69/69 11.5it/s 6.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.4it/s 0.9s
                   all        156        418      0.927      0.825      0.919       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     92/100      1.32G     0.7681     0.4614      1.187         16        640: 100% ━━━━━━━━━━━━ 69/69 13.8it/s 5.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.2it/s 0.9s
                   all        156        418       0.89       0.87      0.921      0.633

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     93/100      1.32G     0.7668     0.4383      1.168         20        640: 100% ━━━━━━━━━━━━ 69/69 14.0it/s 4.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.8it/s 0.9s
                   all        156        418      0.889       0.84      0.901      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     94/100      1.32G     0.7487     0.4296       1.16         20        640: 100% ━━━━━━━━━━━━ 69/69 14.4it/s 4.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.7it/s 0.9s
                   all        156        418      0.887      0.843       0.91      0.626

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     95/100      1.32G     0.7411     0.4259      1.168         12        640: 100% ━━━━━━━━━━━━ 69/69 14.6it/s 4.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.9it/s 0.8s
                   all        156        418      0.886      0.833      0.911      0.628

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     96/100      1.32G     0.7359     0.4329      1.151         21        640: 100% ━━━━━━━━━━━━ 69/69 14.2it/s 4.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 12.0it/s 0.8s
                   all        156        418       0.87      0.861      0.916      0.628

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     97/100      1.32G     0.7305     0.4233      1.159          9        640: 100% ━━━━━━━━━━━━ 69/69 14.0it/s 4.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 12.1it/s 0.8s
                   all        156        418      0.893      0.849      0.916      0.626

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     98/100      1.32G     0.7367     0.4368      1.161         19        640: 100% ━━━━━━━━━━━━ 69/69 14.3it/s 4.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 12.3it/s 0.8s
                   all        156        418      0.894      0.863      0.919       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     99/100      1.32G     0.7158     0.4119      1.126         11        640: 100% ━━━━━━━━━━━━ 69/69 14.2it/s 4.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.8it/s 0.8s
                   all        156        418      0.904      0.835      0.917      0.628

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    100/100      1.32G     0.7244     0.4169      1.143          6        640: 100% ━━━━━━━━━━━━ 69/69 14.4it/s 4.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 12.0it/s 0.8s
                   all        156        418      0.902      0.838      0.917      0.629

Recovery backup updated: yolov8n, epoch 100
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

100 epochs completed in 0.179 hours.
Optimizer stripped from /kaggle/working/amm_yolo/runs/yolov8n/weights/last.pt, 6.5MB
Optimizer stripped from /kaggle/working/amm_yolo/runs/yolov8n/weights/best.pt, 6.5MB

Validating /kaggle/working/amm_yolo/runs/yolov8n/weights/best.pt...
Ultralytics 8.4.184 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
Model summary (fused): 73 layers, 3,132,707 parameters, 0 gradients, 8.6 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.8it/s 2.6s
                   all        156        418      0.888      0.871      0.922      0.632
Speed: 1.7ms preprocess, 8.6ms inference, 0.0ms loss, 2.0ms postprocess per image
Results saved to /kaggle/working/amm_yolo/runs/yolov8n

Completed: yolov8n
Best weights: /kaggle/working/amm_yolo/models/yolov8n_best.pt
Resume checkpoint: /kaggle/working/amm_yolo/models/yolov8n_last.pt
Download this completed-model backup:

/kaggle/working/amm_yolo/amm_yolo_backup_after_yolov8n.zip

=======================================================
Model: yolov8s
Starting a new training run.
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolov8s.pt to 'yolov8s.pt': 100% ━━━━━━━━━━━━ 21.5MB 32.7MB/s 0.7s
New https://pypi.org/project/ultralytics/8.4.194 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.4.184 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/working/amm_yolo/dataset_cardboard_v2/data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=100, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8s.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=yolov8s, nbs=64, nms=None, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=40, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/kaggle/working/amm_yolo/runs, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/amm_yolo/runs/yolov8s, save_frames=False, save_json=False, save_period=10, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=2, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2116435  ultralytics.nn.modules.head.Detect           [1, 16, None, [128, 256, 512]]
Model summary: 129 layers, 11,135,987 parameters, 11,135,971 gradients, 28.6 GFLOPs

Transferred 349/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 748.5±276.0 MB/s, size: 18.2 KB)
train: Scanning /kaggle/working/amm_yolo/dataset_cardboard_v2/train/labels.cache... 550 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 550/550 153.8Mit/s 0.0s
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 472.2±191.1 MB/s, size: 19.6 KB)
val: Scanning /kaggle/working/amm_yolo/dataset_cardboard_v2/valid/labels.cache... 156 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 156/156 50.3Mit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and determining best 'optimizer' and 'lr0' automatically...
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Plotting labels to /kaggle/working/amm_yolo/runs/yolov8s/labels.jpg...
Using 550 train, 156 val images for fraction=1.0 at imgsz=640
Using 2 dataloader workers
Logging results to /kaggle/working/amm_yolo/runs/yolov8s
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/100      1.92G      1.287      2.437      1.547         34        640: 100% ━━━━━━━━━━━━ 69/69 8.7it/s 7.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.2it/s 1.9s
                   all        156        418      0.579      0.438      0.473      0.246

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/100       2.3G      1.402      1.515      1.631         59        640: 100% ━━━━━━━━━━━━ 69/69 10.4it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.7it/s 1.2s
                   all        156        418      0.533      0.399      0.426      0.198

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/100      2.32G      1.488      1.572       1.71         25        640: 100% ━━━━━━━━━━━━ 69/69 10.3it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.7it/s 1.2s
                   all        156        418      0.254      0.421      0.234     0.0781

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/100      2.32G      1.537      1.538      1.771         36        640: 100% ━━━━━━━━━━━━ 69/69 10.3it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.7it/s 1.1s
                   all        156        418      0.438      0.467      0.383      0.193

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/100      2.32G      1.448      1.439      1.696         26        640: 100% ━━━━━━━━━━━━ 69/69 10.2it/s 6.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.9it/s 1.1s
                   all        156        418      0.533       0.38      0.409      0.203

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/100      2.32G      1.428       1.42      1.717         14        640: 100% ━━━━━━━━━━━━ 69/69 10.3it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.8it/s 1.1s
                   all        156        418      0.534      0.557      0.544      0.284

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/100      2.32G      1.425      1.426      1.692         30        640: 100% ━━━━━━━━━━━━ 69/69 10.4it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.0it/s 1.1s
                   all        156        418      0.583      0.596      0.625      0.338

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/100      2.32G      1.394      1.464      1.675         28        640: 100% ━━━━━━━━━━━━ 69/69 10.5it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.9it/s 1.1s
                   all        156        418      0.729      0.677      0.741      0.422

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/100      2.32G      1.398        1.4      1.661         37        640: 100% ━━━━━━━━━━━━ 69/69 10.5it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.0it/s 1.1s
                   all        156        418      0.711      0.625      0.682      0.383

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/100      2.32G      1.348      1.325      1.617         24        640: 100% ━━━━━━━━━━━━ 69/69 10.5it/s 6.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.1it/s 1.1s
                   all        156        418      0.669      0.586      0.663      0.366

Recovery backup updated: yolov8s, epoch 10
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/100      2.32G      1.324      1.268      1.597         33        640: 100% ━━━━━━━━━━━━ 69/69 10.3it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.8it/s 1.1s
                   all        156        418      0.653      0.634      0.665      0.389

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/100      2.32G      1.321       1.26      1.582         15        640: 100% ━━━━━━━━━━━━ 69/69 10.4it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.7it/s 1.1s
                   all        156        418      0.681      0.591      0.632      0.357

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/100      2.32G      1.338      1.291      1.604         34        640: 100% ━━━━━━━━━━━━ 69/69 10.2it/s 6.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.8it/s 1.1s
                   all        156        418      0.705      0.708      0.762      0.447

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/100      2.32G       1.31      1.211      1.584         40        640: 100% ━━━━━━━━━━━━ 69/69 10.1it/s 6.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.8it/s 1.1s
                   all        156        418      0.809      0.663      0.761      0.461

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/100      2.32G      1.261      1.171      1.545         23        640: 100% ━━━━━━━━━━━━ 69/69 10.2it/s 6.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.5it/s 1.2s
                   all        156        418      0.815      0.714      0.802      0.492

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/100      2.32G      1.234      1.118      1.503         29        640: 100% ━━━━━━━━━━━━ 69/69 10.2it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.8it/s 1.1s
                   all        156        418      0.837      0.744      0.832      0.529

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/100      2.32G      1.254      1.081      1.543         48        640: 100% ━━━━━━━━━━━━ 69/69 10.3it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.0it/s 1.1s
                   all        156        418      0.779      0.737        0.8      0.486

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/100      2.32G      1.259      1.121       1.54         26        640: 100% ━━━━━━━━━━━━ 69/69 10.4it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.7it/s 1.1s
                   all        156        418       0.76      0.713      0.796      0.482

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/100      2.32G      1.203      1.112      1.518         47        640: 100% ━━━━━━━━━━━━ 69/69 10.5it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.1it/s 1.1s
                   all        156        418      0.785      0.707      0.808      0.519

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/100      2.32G       1.21      1.086      1.511         48        640: 100% ━━━━━━━━━━━━ 69/69 10.5it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.9it/s 1.1s
                   all        156        418      0.747      0.763      0.818       0.51

Recovery backup updated: yolov8s, epoch 20
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/100      2.32G      1.199       1.08      1.497         23        640: 100% ━━━━━━━━━━━━ 69/69 9.6it/s 7.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.8it/s 1.1s
                   all        156        418      0.834      0.742      0.842      0.527

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/100      2.32G      1.202      1.059        1.5         23        640: 100% ━━━━━━━━━━━━ 69/69 10.4it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.7it/s 1.1s
                   all        156        418      0.864      0.713      0.823      0.527

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/100      2.32G       1.19      1.008      1.493         25        640: 100% ━━━━━━━━━━━━ 69/69 10.2it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.6it/s 1.2s
                   all        156        418      0.831      0.752      0.826      0.525

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/100      2.32G      1.161      1.005      1.488         17        640: 100% ━━━━━━━━━━━━ 69/69 10.2it/s 6.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.8it/s 1.1s
                   all        156        418      0.802      0.777      0.848      0.561

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/100      2.32G      1.145     0.9962      1.477         31        640: 100% ━━━━━━━━━━━━ 69/69 10.0it/s 6.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.5it/s 1.2s
                   all        156        418       0.83      0.718      0.826      0.524

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/100      2.32G      1.206      1.012      1.508         30        640: 100% ━━━━━━━━━━━━ 69/69 10.0it/s 6.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.6it/s 1.2s
                   all        156        418      0.827      0.732      0.832      0.535

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/100      2.32G      1.143     0.9816      1.465         15        640: 100% ━━━━━━━━━━━━ 69/69 9.9it/s 7.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.9it/s 1.1s
                   all        156        418      0.785      0.792      0.848       0.56

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/100      2.32G      1.144     0.9562      1.446         23        640: 100% ━━━━━━━━━━━━ 69/69 10.3it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.7it/s 1.2s
                   all        156        418      0.865      0.756      0.861       0.56

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/100      2.32G      1.117     0.9231      1.426         19        640: 100% ━━━━━━━━━━━━ 69/69 10.3it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.7it/s 1.1s
                   all        156        418      0.851      0.761      0.853      0.567

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/100      2.32G      1.103     0.8872      1.426         30        640: 100% ━━━━━━━━━━━━ 69/69 10.4it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.7it/s 1.2s
                   all        156        418      0.896       0.78      0.884       0.58

Recovery backup updated: yolov8s, epoch 30
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/100      2.32G      1.096     0.8824      1.436         30        640: 100% ━━━━━━━━━━━━ 69/69 10.1it/s 6.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.8it/s 1.1s
                   all        156        418      0.867       0.81      0.881       0.58

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/100      2.32G      1.115     0.9324      1.456         24        640: 100% ━━━━━━━━━━━━ 69/69 10.1it/s 6.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.6it/s 1.2s
                   all        156        418      0.875      0.771      0.867      0.573

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     33/100      2.32G      1.114     0.8849      1.428         37        640: 100% ━━━━━━━━━━━━ 69/69 10.1it/s 6.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.7it/s 1.1s
                   all        156        418      0.908      0.766      0.869      0.571

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     34/100      2.32G      1.098     0.9134      1.431         25        640: 100% ━━━━━━━━━━━━ 69/69 10.0it/s 6.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.6it/s 1.2s
                   all        156        418      0.904      0.809      0.885      0.594

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     35/100      2.32G      1.068     0.8943      1.405         43        640: 100% ━━━━━━━━━━━━ 69/69 10.0it/s 6.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.8it/s 1.1s
                   all        156        418      0.892      0.837      0.891      0.596

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     36/100      2.32G      1.059     0.8237       1.41         31        640: 100% ━━━━━━━━━━━━ 69/69 10.2it/s 6.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.7it/s 1.2s
                   all        156        418      0.877      0.811      0.882      0.572

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     37/100      2.32G      1.085      0.833      1.393         45        640: 100% ━━━━━━━━━━━━ 69/69 10.2it/s 6.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.8it/s 1.1s
                   all        156        418      0.877      0.789      0.895      0.589

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     38/100      2.32G      1.085     0.8418      1.419         39        640: 100% ━━━━━━━━━━━━ 69/69 10.2it/s 6.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.6it/s 1.2s
                   all        156        418      0.838      0.811      0.878      0.589

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     39/100      2.32G      1.092     0.8429      1.402         23        640: 100% ━━━━━━━━━━━━ 69/69 10.2it/s 6.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.4it/s 1.2s
                   all        156        418      0.837      0.775      0.853      0.544

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     40/100      2.32G      1.034     0.8389      1.392         36        640: 100% ━━━━━━━━━━━━ 69/69 10.2it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.7it/s 1.2s
                   all        156        418       0.89      0.816      0.906      0.618

Recovery backup updated: yolov8s, epoch 40
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     41/100      2.32G       1.06      0.836      1.406         28        640: 100% ━━━━━━━━━━━━ 69/69 9.8it/s 7.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.9it/s 1.1s
                   all        156        418      0.882      0.761      0.866      0.554

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     42/100      2.32G      1.103     0.8232      1.401         27        640: 100% ━━━━━━━━━━━━ 69/69 10.1it/s 6.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.7it/s 1.1s
                   all        156        418      0.806      0.836      0.879       0.58

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     43/100      2.32G      1.043     0.8152      1.366         18        640: 100% ━━━━━━━━━━━━ 69/69 10.2it/s 6.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.7it/s 1.1s
                   all        156        418      0.881      0.782      0.884      0.595

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     44/100      2.32G      1.058     0.8395      1.408         34        640: 100% ━━━━━━━━━━━━ 69/69 10.1it/s 6.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.9it/s 1.1s
                   all        156        418      0.824      0.703      0.809      0.534

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     45/100      2.32G      1.044      0.812      1.391         25        640: 100% ━━━━━━━━━━━━ 69/69 10.1it/s 6.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.8it/s 1.1s
                   all        156        418      0.846      0.782      0.866      0.553

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     46/100      2.32G      1.035     0.7776       1.37         23        640: 100% ━━━━━━━━━━━━ 69/69 10.2it/s 6.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.7it/s 1.1s
                   all        156        418      0.858       0.78      0.861      0.577

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     47/100      2.32G      1.034     0.7987      1.376         24        640: 100% ━━━━━━━━━━━━ 69/69 10.3it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.1it/s 1.1s
                   all        156        418      0.872       0.77      0.876      0.557

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     48/100      2.32G       1.04     0.7909      1.381         29        640: 100% ━━━━━━━━━━━━ 69/69 10.3it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.9it/s 1.1s
                   all        156        418      0.891      0.821      0.916      0.616

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     49/100      2.32G      1.039     0.7513      1.376         26        640: 100% ━━━━━━━━━━━━ 69/69 10.3it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.7it/s 1.1s
                   all        156        418      0.879      0.848      0.904      0.609

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     50/100      2.32G       1.06     0.7875      1.363         36        640: 100% ━━━━━━━━━━━━ 69/69 10.3it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.0it/s 1.1s
                   all        156        418      0.903      0.805      0.887      0.601

Recovery backup updated: yolov8s, epoch 50
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     51/100      2.32G      1.027     0.7928      1.377         34        640: 100% ━━━━━━━━━━━━ 69/69 10.4it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.0it/s 1.1s
                   all        156        418      0.874      0.828      0.896      0.596

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     52/100      2.32G      1.007     0.7742      1.364         24        640: 100% ━━━━━━━━━━━━ 69/69 10.3it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.9it/s 1.1s
                   all        156        418      0.929      0.785      0.892       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     53/100      2.32G      1.019     0.7633      1.363         37        640: 100% ━━━━━━━━━━━━ 69/69 10.3it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.8it/s 1.1s
                   all        156        418      0.925      0.811        0.9      0.608

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     54/100      2.32G      1.022     0.7433      1.355         29        640: 100% ━━━━━━━━━━━━ 69/69 10.2it/s 6.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.7it/s 1.1s
                   all        156        418      0.925      0.801      0.917      0.609

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     55/100      2.32G     0.9721     0.7211      1.335         40        640: 100% ━━━━━━━━━━━━ 69/69 10.2it/s 6.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.9it/s 1.1s
                   all        156        418      0.883      0.821      0.911      0.616

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     56/100      2.32G      1.009     0.7142      1.337         30        640: 100% ━━━━━━━━━━━━ 69/69 10.2it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.1it/s 1.1s
                   all        156        418      0.866      0.844      0.908       0.62

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     57/100      2.32G     0.9819     0.6935      1.326         24        640: 100% ━━━━━━━━━━━━ 69/69 10.4it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.2it/s 1.1s
                   all        156        418      0.904      0.833      0.901      0.618

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     58/100      2.32G     0.9835      0.719      1.328         35        640: 100% ━━━━━━━━━━━━ 69/69 10.4it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.0it/s 1.1s
                   all        156        418      0.899      0.786      0.886      0.602

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     59/100      2.32G     0.9615     0.6971      1.326         30        640: 100% ━━━━━━━━━━━━ 69/69 10.5it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.3it/s 1.1s
                   all        156        418      0.908      0.824        0.9      0.616

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     60/100      2.32G      0.954     0.6626      1.297         35        640: 100% ━━━━━━━━━━━━ 69/69 10.4it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.1it/s 1.1s
                   all        156        418      0.888       0.83      0.905       0.61

Recovery backup updated: yolov8s, epoch 60
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     61/100      2.32G     0.9877     0.6999      1.337         17        640: 100% ━━━━━━━━━━━━ 69/69 10.4it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.2it/s 1.1s
                   all        156        418      0.889      0.845      0.912       0.62

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     62/100      2.32G     0.9686     0.6856      1.316         28        640: 100% ━━━━━━━━━━━━ 69/69 10.4it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.0it/s 1.1s
                   all        156        418       0.91      0.825      0.907      0.604

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     63/100      2.32G     0.9591     0.6792      1.309         22        640: 100% ━━━━━━━━━━━━ 69/69 10.3it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.0it/s 1.1s
                   all        156        418       0.92      0.794      0.874      0.599

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     64/100      2.32G     0.9431     0.6717      1.303         27        640: 100% ━━━━━━━━━━━━ 69/69 10.2it/s 6.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.1it/s 1.1s
                   all        156        418      0.899      0.816      0.893      0.614

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     65/100      2.32G     0.9461     0.6633      1.312         22        640: 100% ━━━━━━━━━━━━ 69/69 10.2it/s 6.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.2it/s 1.1s
                   all        156        418      0.929      0.825      0.895      0.615

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     66/100      2.32G      0.936     0.6547      1.305         40        640: 100% ━━━━━━━━━━━━ 69/69 10.3it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.3it/s 1.1s
                   all        156        418      0.899      0.818      0.895      0.606

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     67/100      2.32G      0.942      0.672      1.298         38        640: 100% ━━━━━━━━━━━━ 69/69 10.4it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.1it/s 1.1s
                   all        156        418      0.913      0.801      0.893      0.609

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     68/100      2.32G     0.9301     0.6449      1.292         34        640: 100% ━━━━━━━━━━━━ 69/69 10.3it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.1it/s 1.1s
                   all        156        418      0.917      0.816      0.903      0.611

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     69/100      2.32G     0.9453     0.6504      1.301         27        640: 100% ━━━━━━━━━━━━ 69/69 10.4it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.0it/s 1.1s
                   all        156        418      0.902      0.844      0.909      0.634

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     70/100      2.32G     0.9421     0.6579        1.3         30        640: 100% ━━━━━━━━━━━━ 69/69 10.5it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.1it/s 1.1s
                   all        156        418      0.911      0.821      0.889      0.614

Recovery backup updated: yolov8s, epoch 70
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     71/100      2.32G      0.899     0.6357      1.267         44        640: 100% ━━━━━━━━━━━━ 69/69 10.4it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.0it/s 1.1s
                   all        156        418      0.902       0.83      0.894      0.621

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     72/100      2.32G     0.9133     0.6095      1.276         33        640: 100% ━━━━━━━━━━━━ 69/69 10.4it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.2it/s 1.1s
                   all        156        418      0.878      0.856      0.889      0.609

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     73/100      2.32G     0.9088     0.6159      1.274         34        640: 100% ━━━━━━━━━━━━ 69/69 10.3it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.2it/s 1.1s
                   all        156        418      0.882      0.841       0.89      0.619

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     74/100      2.32G     0.9329      0.611      1.279         35        640: 100% ━━━━━━━━━━━━ 69/69 10.2it/s 6.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.9it/s 1.1s
                   all        156        418      0.892      0.859      0.906      0.625

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     75/100      2.32G      0.889     0.6028      1.266         32        640: 100% ━━━━━━━━━━━━ 69/69 10.2it/s 6.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.1it/s 1.1s
                   all        156        418      0.899      0.823      0.907      0.618

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     76/100      2.32G      0.869     0.5801      1.255         30        640: 100% ━━━━━━━━━━━━ 69/69 10.2it/s 6.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.1it/s 1.1s
                   all        156        418      0.864       0.83       0.89      0.606

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     77/100      2.32G     0.9005     0.6054      1.272         25        640: 100% ━━━━━━━━━━━━ 69/69 10.4it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.0it/s 1.1s
                   all        156        418      0.914       0.83      0.906      0.619

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     78/100      2.32G     0.8832     0.6014      1.268         40        640: 100% ━━━━━━━━━━━━ 69/69 10.3it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.3it/s 1.1s
                   all        156        418      0.887      0.861      0.905      0.631

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     79/100      2.32G     0.8646      0.579       1.26         22        640: 100% ━━━━━━━━━━━━ 69/69 10.5it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.0it/s 1.1s
                   all        156        418      0.917      0.823      0.897      0.618

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     80/100      2.32G     0.8828     0.5702      1.254         34        640: 100% ━━━━━━━━━━━━ 69/69 10.5it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.0it/s 1.1s
                   all        156        418      0.906      0.827      0.892      0.612

Recovery backup updated: yolov8s, epoch 80
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     81/100      2.32G     0.8689     0.5939      1.231         28        640: 100% ━━━━━━━━━━━━ 69/69 10.3it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.0it/s 1.1s
                   all        156        418      0.912       0.82      0.901      0.621

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     82/100      2.32G     0.8523      0.577      1.241         23        640: 100% ━━━━━━━━━━━━ 69/69 10.3it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.0it/s 1.1s
                   all        156        418      0.902      0.825      0.897      0.624

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     83/100      2.32G     0.8526     0.5825      1.246         44        640: 100% ━━━━━━━━━━━━ 69/69 10.3it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.2it/s 1.1s
                   all        156        418      0.867      0.842       0.89       0.62

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     84/100      2.32G      0.826     0.5565      1.217         24        640: 100% ━━━━━━━━━━━━ 69/69 10.2it/s 6.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.0it/s 1.1s
                   all        156        418      0.875      0.861      0.899      0.629

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     85/100      2.32G     0.8705     0.5785      1.251         40        640: 100% ━━━━━━━━━━━━ 69/69 10.2it/s 6.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.0it/s 1.1s
                   all        156        418      0.906      0.837        0.9      0.626

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     86/100      2.32G     0.8534     0.5551      1.227         39        640: 100% ━━━━━━━━━━━━ 69/69 10.3it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.9it/s 1.1s
                   all        156        418      0.914      0.823      0.895      0.628

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     87/100      2.32G     0.8394      0.561      1.221         31        640: 100% ━━━━━━━━━━━━ 69/69 10.4it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.4it/s 1.1s
                   all        156        418      0.904      0.835      0.892      0.622

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     88/100      2.32G     0.8336      0.537      1.217         27        640: 100% ━━━━━━━━━━━━ 69/69 10.4it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.2it/s 1.1s
                   all        156        418      0.883      0.866      0.905      0.635

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     89/100      2.32G     0.8164     0.5542       1.21         28        640: 100% ━━━━━━━━━━━━ 69/69 10.4it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.2it/s 1.1s
                   all        156        418      0.902      0.859      0.912      0.635

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     90/100      2.32G     0.8199     0.5467      1.208         31        640: 100% ━━━━━━━━━━━━ 69/69 10.5it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.0it/s 1.1s
                   all        156        418      0.929      0.846      0.903      0.631

Recovery backup updated: yolov8s, epoch 90
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     91/100      2.32G      0.752      0.465      1.198         10        640: 100% ━━━━━━━━━━━━ 69/69 9.4it/s 7.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.0it/s 1.1s
                   all        156        418      0.922      0.828      0.883      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     92/100      2.32G     0.7337     0.4453      1.177         16        640: 100% ━━━━━━━━━━━━ 69/69 10.4it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.0it/s 1.1s
                   all        156        418      0.929      0.842      0.901       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     93/100      2.32G       0.73     0.4164      1.164         20        640: 100% ━━━━━━━━━━━━ 69/69 10.4it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.1it/s 1.1s
                   all        156        418      0.889       0.84      0.889      0.628

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     94/100      2.32G     0.7292     0.4149      1.171         20        640: 100% ━━━━━━━━━━━━ 69/69 10.3it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.0it/s 1.1s
                   all        156        418      0.899      0.852      0.901      0.634

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     95/100      2.32G      0.712      0.405      1.166         12        640: 100% ━━━━━━━━━━━━ 69/69 10.3it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.9it/s 1.1s
                   all        156        418      0.923      0.835      0.906      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     96/100      2.32G      0.707     0.4076      1.158         21        640: 100% ━━━━━━━━━━━━ 69/69 10.4it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.2it/s 1.1s
                   all        156        418       0.89      0.847      0.909      0.641

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     97/100      2.32G     0.7015     0.4017      1.161          9        640: 100% ━━━━━━━━━━━━ 69/69 10.5it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.2it/s 1.1s
                   all        156        418      0.878      0.861      0.909      0.635

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     98/100      2.32G     0.7155     0.4228      1.165         19        640: 100% ━━━━━━━━━━━━ 69/69 10.5it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.3it/s 1.1s
                   all        156        418      0.911      0.842      0.912      0.634

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     99/100      2.32G     0.6803      0.396      1.128         11        640: 100% ━━━━━━━━━━━━ 69/69 10.5it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 9.3it/s 1.1s
                   all        156        418      0.895      0.849      0.911      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    100/100      2.32G     0.6949     0.3943      1.147          6        640: 100% ━━━━━━━━━━━━ 69/69 10.6it/s 6.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.9it/s 1.1s
                   all        156        418       0.93      0.833      0.911      0.637

Recovery backup updated: yolov8s, epoch 100
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

100 epochs completed in 0.263 hours.
Optimizer stripped from /kaggle/working/amm_yolo/runs/yolov8s/weights/last.pt, 22.5MB
Optimizer stripped from /kaggle/working/amm_yolo/runs/yolov8s/weights/best.pt, 22.5MB

Validating /kaggle/working/amm_yolo/runs/yolov8s/weights/best.pt...
Ultralytics 8.4.184 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
Model summary (fused): 72 layers, 11,125,971 parameters, 0 gradients, 28.4 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.7it/s 2.7s
                   all        156        418      0.892      0.847       0.91       0.64
Speed: 1.3ms preprocess, 8.8ms inference, 0.0ms loss, 3.7ms postprocess per image
Results saved to /kaggle/working/amm_yolo/runs/yolov8s

Completed: yolov8s
Best weights: /kaggle/working/amm_yolo/models/yolov8s_best.pt
Resume checkpoint: /kaggle/working/amm_yolo/models/yolov8s_last.pt
Download this completed-model backup:

/kaggle/working/amm_yolo/amm_yolo_backup_after_yolov8s.zip

=======================================================
Model: yolov8m
Starting a new training run.
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolov8m.pt to 'yolov8m.pt': 100% ━━━━━━━━━━━━ 49.7MB 57.8MB/s 0.9s
New https://pypi.org/project/ultralytics/8.4.194 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.4.184 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/working/amm_yolo/dataset_cardboard_v2/data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=100, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=yolov8m, nbs=64, nms=None, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=40, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/kaggle/working/amm_yolo/runs, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/amm_yolo/runs/yolov8m, save_frames=False, save_json=False, save_period=10, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=2, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3776275  ultralytics.nn.modules.head.Detect           [1, 16, None, [192, 384, 576]]
Model summary: 169 layers, 25,856,899 parameters, 25,856,883 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 593.9±209.0 MB/s, size: 18.2 KB)
train: Scanning /kaggle/working/amm_yolo/dataset_cardboard_v2/train/labels.cache... 550 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 550/550 164.8Mit/s 0.0s
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 486.0±234.6 MB/s, size: 19.6 KB)
val: Scanning /kaggle/working/amm_yolo/dataset_cardboard_v2/valid/labels.cache... 156 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 156/156 54.5Mit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and determining best 'optimizer' and 'lr0' automatically...
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.0005), 83 bias(decay=0.0)
Plotting labels to /kaggle/working/amm_yolo/runs/yolov8m/labels.jpg...
Using 550 train, 156 val images for fraction=1.0 at imgsz=640
Using 2 dataloader workers
Logging results to /kaggle/working/amm_yolo/runs/yolov8m
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/100      3.51G      1.372      1.665      1.668         34        640: 100% ━━━━━━━━━━━━ 69/69 4.6it/s 15.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 4.4it/s 2.3s
                   all        156        418      0.387      0.388      0.339      0.156

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/100      4.08G      1.559      1.684      1.804         59        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.3it/s 1.9s
                   all        156        418       0.17      0.254      0.116     0.0381

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/100      4.09G      1.606      1.712       1.85         25        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.4it/s 1.9s
                   all        156        418       0.22      0.251       0.13     0.0447

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/100      4.09G      1.596      1.664      1.844         36        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.4it/s 1.9s
                   all        156        418       0.11     0.0868     0.0245    0.00742

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/100      4.09G      1.526      1.592      1.804         26        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.3it/s 1.9s
                   all        156        418      0.514      0.493      0.447      0.226

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/100      4.09G      1.484      1.532      1.794         14        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.3it/s 1.9s
                   all        156        418      0.596      0.545      0.576      0.295

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/100      4.09G      1.453      1.537      1.784         30        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.3it/s 1.9s
                   all        156        418       0.56      0.529      0.563      0.305

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/100      4.09G      1.438       1.52      1.767         28        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.3it/s 1.9s
                   all        156        418      0.594      0.536      0.536      0.277

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/100      4.09G      1.433      1.496       1.73         37        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.3it/s 1.9s
                   all        156        418      0.609      0.543      0.603      0.315

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/100      4.09G      1.401      1.453      1.711         24        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.3it/s 1.9s
                   all        156        418      0.724      0.576      0.662      0.372

Recovery backup updated: yolov8m, epoch 10
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/100      4.09G      1.345      1.336       1.66         33        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418       0.75      0.691      0.743      0.451

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/100      4.09G      1.367      1.361      1.681         15        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.624      0.651      0.647      0.358

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/100      4.09G      1.394      1.353      1.705         34        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.4it/s 1.8s
                   all        156        418      0.752      0.676      0.749      0.427

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/100      4.09G      1.356      1.352      1.678         40        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.4it/s 1.8s
                   all        156        418      0.714      0.598      0.682      0.392

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/100      4.09G      1.299      1.276      1.624         23        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.4it/s 1.8s
                   all        156        418      0.793      0.584      0.729       0.42

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/100      4.09G      1.309      1.259      1.613         29        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.4it/s 1.9s
                   all        156        418      0.779      0.684      0.777      0.482

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/100      4.09G      1.284      1.195      1.619         48        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.4it/s 1.8s
                   all        156        418      0.747      0.629      0.719      0.406

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/100      4.09G      1.307      1.206      1.624         26        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.4it/s 1.9s
                   all        156        418      0.705      0.734       0.79      0.495

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/100      4.09G      1.242      1.183      1.586         47        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.4it/s 1.9s
                   all        156        418      0.815      0.645      0.763      0.468

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/100      4.09G      1.226      1.175      1.569         48        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.4it/s 1.9s
                   all        156        418      0.782      0.722      0.783      0.493

Recovery backup updated: yolov8m, epoch 20
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/100      4.09G      1.216      1.151      1.556         23        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.857      0.667      0.805      0.501

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/100      4.09G      1.221      1.123      1.561         23        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.816      0.765      0.841       0.51

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/100      4.09G       1.25       1.09      1.575         25        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.4it/s 1.8s
                   all        156        418      0.821      0.723      0.837      0.532

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/100      4.09G      1.207      1.105      1.559         17        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.856      0.734      0.832      0.528

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/100      4.09G      1.185      1.063      1.554         31        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.843      0.747      0.833      0.527

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/100      4.09G      1.228      1.065      1.554         30        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.4it/s 1.8s
                   all        156        418      0.863      0.768       0.87      0.554

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/100      4.09G       1.18      1.036      1.517         15        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.799      0.768      0.842      0.527

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/100      4.09G      1.186      1.047      1.524         23        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.4it/s 1.8s
                   all        156        418      0.814      0.758       0.86       0.55

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/100      4.09G      1.159     0.9941      1.496         19        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.4it/s 1.8s
                   all        156        418      0.824      0.753      0.827      0.547

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/100      4.09G      1.135     0.9731       1.49         30        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.4it/s 1.8s
                   all        156        418      0.857      0.772      0.862       0.57

Recovery backup updated: yolov8m, epoch 30
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/100      4.09G      1.128     0.9557      1.481         30        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.864      0.742      0.844      0.546

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/100      4.09G      1.148      1.004      1.513         24        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.823      0.787      0.851      0.548

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     33/100      4.09G      1.165      0.987      1.501         37        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.811       0.78       0.86      0.563

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     34/100      4.09G      1.133     0.9716      1.502         25        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 13.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.881      0.818      0.895      0.599

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     35/100      4.09G      1.096     0.9265       1.46         43        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.917      0.746      0.875      0.568

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     36/100      4.09G      1.099     0.8949      1.473         31        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.796      0.706      0.793      0.483

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     37/100      4.09G      1.113     0.8881      1.446         45        640: 100% ━━━━━━━━━━━━ 69/69 4.8it/s 14.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.4it/s 1.8s
                   all        156        418      0.888      0.741      0.878      0.596

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     38/100      4.09G      1.119     0.9111      1.479         39        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.4it/s 1.8s
                   all        156        418      0.831       0.77      0.861      0.558

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     39/100      4.09G       1.13     0.9036      1.469         23        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.906      0.754      0.883      0.581

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     40/100      4.09G       1.08     0.8678      1.457         36        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.4it/s 1.9s
                   all        156        418       0.84      0.781      0.871       0.59

Recovery backup updated: yolov8m, epoch 40
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     41/100      4.09G      1.088     0.8754      1.467         28        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.6it/s 1.8s
                   all        156        418      0.839      0.783      0.872      0.568

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     42/100      4.09G      1.116     0.8878      1.463         27        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.831      0.818      0.884      0.587

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     43/100      4.09G      1.063      0.852      1.418         18        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418       0.86      0.751      0.862      0.572

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     44/100      4.09G      1.087     0.9038      1.466         34        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.842       0.78      0.875      0.589

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     45/100      4.09G      1.085     0.8925       1.46         25        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.866      0.778      0.872      0.578

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     46/100      4.09G      1.054      0.865      1.426         23        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418       0.85      0.773      0.866      0.549

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     47/100      4.09G      1.056     0.8552      1.433         24        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.884      0.803      0.884      0.587

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     48/100      4.09G      1.054     0.8254      1.427         29        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.904      0.766      0.896      0.607

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     49/100      4.09G      1.051     0.7894      1.428         26        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.4it/s 1.8s
                   all        156        418      0.889      0.763      0.877       0.58

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     50/100      4.09G      1.078     0.8229      1.419         36        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.895      0.792      0.872       0.58

Recovery backup updated: yolov8m, epoch 50
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     51/100      4.09G      1.057     0.8298       1.43         34        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.877       0.82      0.883      0.584

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     52/100      4.09G      1.044     0.8314      1.426         24        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.6it/s 1.8s
                   all        156        418      0.865      0.809      0.867       0.58

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     53/100      4.09G      1.046     0.7806      1.412         37        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.6it/s 1.8s
                   all        156        418      0.903      0.821      0.903       0.61

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     54/100      4.09G      1.036      0.779      1.405         29        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.851      0.806      0.885      0.598

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     55/100      4.09G     0.9918     0.7585      1.387         40        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.891      0.821      0.914      0.622

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     56/100      4.09G      1.028     0.7728       1.39         30        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.881      0.794      0.893      0.603

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     57/100      4.09G      1.007     0.7474      1.386         24        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.4it/s 1.9s
                   all        156        418       0.83      0.828      0.884      0.596

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     58/100      4.09G      1.016     0.7605      1.383         35        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418       0.89      0.831      0.904      0.608

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     59/100      4.09G     0.9889     0.7321      1.374         30        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.848      0.835      0.893      0.608

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     60/100      4.09G     0.9909     0.7136      1.351         35        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.4it/s 1.8s
                   all        156        418      0.885      0.831      0.899      0.606

Recovery backup updated: yolov8m, epoch 60
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     61/100      4.09G      1.002     0.7265      1.379         17        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.6it/s 1.8s
                   all        156        418      0.887      0.842      0.914      0.629

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     62/100      4.09G     0.9856     0.7074      1.363         28        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.6it/s 1.8s
                   all        156        418      0.909      0.834      0.922      0.621

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     63/100      4.09G     0.9703     0.7059       1.36         22        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.6it/s 1.8s
                   all        156        418      0.875      0.797      0.897      0.607

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     64/100      4.09G     0.9646     0.7039      1.361         27        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.6it/s 1.8s
                   all        156        418      0.893      0.849      0.911       0.62

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     65/100      4.09G     0.9544     0.6963      1.357         22        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418        0.9       0.84      0.906      0.616

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     66/100      4.09G     0.9627     0.7017      1.358         40        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418       0.86      0.835      0.897      0.606

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     67/100      4.09G     0.9814     0.7234      1.359         38        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.903      0.821      0.916      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     68/100      4.09G     0.9596     0.6888      1.346         34        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.4it/s 1.8s
                   all        156        418      0.896      0.864       0.92      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     69/100      4.09G     0.9561     0.6766      1.347         27        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.4it/s 1.8s
                   all        156        418      0.876      0.847      0.905       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     70/100      4.09G     0.9555     0.6869      1.342         30        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.892      0.849      0.889      0.608

Recovery backup updated: yolov8m, epoch 70
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     71/100      4.09G     0.9251     0.6657      1.313         44        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.6it/s 1.8s
                   all        156        418      0.896      0.846      0.898      0.622

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     72/100      4.09G     0.9318     0.6538      1.328         33        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.908      0.849      0.922       0.64

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     73/100      4.09G     0.9266      0.649      1.327         34        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.921      0.849      0.924      0.646

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     74/100      4.09G      0.938     0.6597      1.322         35        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.923      0.828      0.912      0.625

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     75/100      4.09G     0.9104     0.6468      1.319         32        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.904      0.854      0.914      0.618

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     76/100      4.09G     0.8923     0.6227      1.306         30        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.929      0.818       0.91      0.604

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     77/100      4.09G     0.9262     0.6469      1.324         25        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.919      0.847      0.913      0.637

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     78/100      4.09G     0.9123     0.6375      1.314         40        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.946      0.818      0.909      0.627

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     79/100      4.09G     0.8879     0.6154      1.305         22        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.913       0.83        0.9      0.615

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     80/100      4.09G     0.8979     0.5967        1.3         34        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.891      0.838      0.912      0.625

Recovery backup updated: yolov8m, epoch 80
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     81/100      4.09G       0.88     0.6137      1.271         28        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.6it/s 1.8s
                   all        156        418      0.893      0.838      0.914      0.642

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     82/100      4.09G     0.8732     0.5966      1.284         23        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.6it/s 1.8s
                   all        156        418      0.909      0.847      0.921      0.629

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     83/100      4.09G     0.8866     0.6107      1.304         44        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.6it/s 1.8s
                   all        156        418      0.897      0.857      0.925      0.638

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     84/100      4.09G     0.8423     0.5768       1.26         24        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.6it/s 1.8s
                   all        156        418        0.9      0.866      0.921      0.633

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     85/100      4.09G     0.8598     0.5929      1.281         40        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 13.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.881      0.849      0.909      0.634

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     86/100      4.09G     0.8708     0.5726      1.275         39        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.886      0.873      0.924      0.643

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     87/100      4.09G     0.8609      0.587      1.268         31        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.938      0.816      0.921      0.631

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     88/100      4.09G     0.8663     0.5764      1.273         27        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.904      0.876      0.937       0.65

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     89/100      4.09G     0.8392     0.5798      1.261         28        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418        0.9      0.868      0.934      0.649

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     90/100      4.09G     0.8342     0.5694      1.246         31        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418       0.94      0.823      0.918      0.636

Recovery backup updated: yolov8m, epoch 90
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     91/100      4.09G     0.7683     0.4821      1.246         10        640: 100% ━━━━━━━━━━━━ 69/69 4.8it/s 14.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.6it/s 1.8s
                   all        156        418      0.953      0.822      0.923      0.638

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     92/100      4.09G     0.7539     0.4559      1.225         16        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.929      0.844      0.927      0.642

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     93/100      4.09G     0.7496     0.4295      1.202         20        640: 100% ━━━━━━━━━━━━ 69/69 5.0it/s 13.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.887      0.868      0.923      0.634

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     94/100      4.09G     0.7517     0.4298      1.223         20        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 13.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.6it/s 1.8s
                   all        156        418      0.926      0.837      0.922      0.641

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     95/100      4.09G     0.7236     0.4295      1.205         12        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.932      0.851      0.928      0.644

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     96/100      4.09G     0.7146      0.425      1.188         21        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.941      0.843      0.927      0.641

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     97/100      4.09G     0.7194     0.4203      1.202          9        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.928      0.849      0.919      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     98/100      4.09G     0.7239     0.4333      1.208         19        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.924      0.842      0.923      0.634

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     99/100      4.09G     0.6998     0.4007      1.168         11        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418      0.925      0.844      0.922      0.634

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    100/100      4.09G     0.7065     0.4033      1.181          6        640: 100% ━━━━━━━━━━━━ 69/69 4.9it/s 14.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        156        418       0.92      0.842      0.922      0.634

Recovery backup updated: yolov8m, epoch 100
Download the recovery ZIP if needed:

/kaggle/working/amm_yolo/amm_yolo_recovery_latest.zip

100 epochs completed in 0.539 hours.
Optimizer stripped from /kaggle/working/amm_yolo/runs/yolov8m/weights/last.pt, 52.0MB
Optimizer stripped from /kaggle/working/amm_yolo/runs/yolov8m/weights/best.pt, 52.0MB

Validating /kaggle/working/amm_yolo/runs/yolov8m/weights/best.pt...
Ultralytics 8.4.184 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
Model summary (fused): 92 layers, 25,840,339 parameters, 0 gradients, 78.7 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.0it/s 3.3s
                   all        156        418      0.904      0.876      0.936      0.651
Speed: 1.5ms preprocess, 10.8ms inference, 0.0ms loss, 4.1ms postprocess per image
Results saved to /kaggle/working/amm_yolo/runs/yolov8m

Completed: yolov8m
Best weights: /kaggle/working/amm_yolo/models/yolov8m_best.pt
Resume checkpoint: /kaggle/working/amm_yolo/models/yolov8m_last.pt
Download this completed-model backup:

/kaggle/working/amm_yolo/amm_yolo_backup_after_yolov8m.zip

Training stage finished.

# Training Evaluation

In [10]:
training_rows = []
EVAL_DEVICE = 0 if torch.cuda.is_available() else "cpu"
EVAL_IMGSZ = 640  # Match the training configuration in this original code.
EVAL_BATCH = 8    # Match the training configuration in this original code.

for model_name in MODEL_CHECKPOINTS:
    weights = MODEL_DIR / f"{model_name}_best.pt"

    if not weights.is_file():
        raise FileNotFoundError(
            f"Required checkpoint for {model_name} was not found: {weights}. "
            "Run/fix CHECKPOINTS UPDATE before evaluation."
        )

    print(f"Training evaluation: {model_name}")
    model = YOLO(str(weights))

    try:
        metrics = model.val(
            data=str(DATA_YAML),
            split="train",
            imgsz=EVAL_IMGSZ,
            batch=EVAL_BATCH,
            device=EVAL_DEVICE,
            workers=2,
            plots=True,
            project=str(RUNS_DIR / "training_evaluation"),
            name=model_name,
            exist_ok=True,
            verbose=True,
        )

        training_rows.append({
            "Model": model_name,
            "Precision": float(metrics.box.mp),
            "Recall": float(metrics.box.mr),
            "mAP50": float(metrics.box.map50),
            "mAP50-95": float(metrics.box.map),
            "Inference ms/image": float(metrics.speed["inference"]),
        })

    finally:
        del model
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

training_evaluation = pd.DataFrame(training_rows)
if training_evaluation.empty:
    raise RuntimeError("Training evaluation produced no results.")

training_evaluation = training_evaluation.round(4).sort_values(
    "mAP50-95", ascending=False
)
display(training_evaluation)
training_evaluation.to_csv(
    WORK_DIR / "training_evaluation.csv", index=False
)
print("Training evaluation saved:", WORK_DIR / "training_evaluation.csv")

Training evaluation: yolov8n
Ultralytics 8.4.184 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
Model summary (fused): 73 layers, 3,132,707 parameters, 0 gradients, 8.6 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 698.9±133.3 MB/s, size: 18.7 KB)
val: Scanning /kaggle/working/amm_yolo/dataset_cardboard_v2/train/labels.cache... 550 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 550/550 192.2Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 69/69 12.7it/s 5.4s
                   all        550       1505      0.978      0.971      0.993      0.795
Speed: 1.1ms preprocess, 4.2ms inference, 0.0ms loss, 0.9ms postprocess per image
Results saved to /kaggle/working/amm_yolo/runs/training_evaluation/yolov8n
Training evaluation: yolov8s
Ultralytics 8.4.184 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
Model summary (fused): 72 layers, 11,125,971 parameters, 0 gradients, 28.4 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 607.2±251.9 MB/s, size: 17.4 KB)
val: Scanning /kaggle/working/amm_yolo/dataset_cardboard_v2/train/labels.cache... 550 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 550/550 192.2Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 69/69 8.2it/s 8.4s
                   all        550       1505      0.981      0.985      0.994      0.827
Speed: 1.3ms preprocess, 9.6ms inference, 0.0ms loss, 1.3ms postprocess per image
Results saved to /kaggle/working/amm_yolo/runs/training_evaluation/yolov8s
Training evaluation: yolov8m
Ultralytics 8.4.184 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
Model summary (fused): 92 layers, 25,840,339 parameters, 0 gradients, 78.7 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 641.2±372.0 MB/s, size: 20.7 KB)
val: Scanning /kaggle/working/amm_yolo/dataset_cardboard_v2/train/labels.cache... 550 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 550/550 164.8Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 69/69 4.1it/s 16.9s
                   all        550       1505      0.973      0.967      0.992      0.796
Speed: 1.2ms preprocess, 25.5ms inference, 0.0ms loss, 0.9ms postprocess per image
Results saved to /kaggle/working/amm_yolo/runs/training_evaluation/yolov8m

     Model  Precision  Recall   mAP50  mAP50-95  Inference ms/image
1  yolov8s     0.9814  0.9854  0.9937    0.8266              9.5856
2  yolov8m     0.9732  0.9667  0.9919    0.7958             25.5467
0  yolov8n     0.9784  0.9714  0.9927    0.7947              4.1732

Training evaluation saved: /kaggle/working/amm_yolo/training_evaluation.csv

# MODEL COMPARESION (Validation Evaluation)

In [11]:
comparison_rows = []

for model_name in MODEL_CHECKPOINTS:
    weights = MODEL_DIR / f"{model_name}_best.pt"

    if not weights.exists():
        print(f"Skipping {model_name}: no saved weights.")
        continue

    print(f"Evaluating {model_name}...")

    model = YOLO(str(weights))

    try:
        metrics = model.val(
            data=str(DATA_YAML),
            split="val",
            imgsz=640,
            batch=8,
            device=0,
            plots=True,
            project=str(RUNS_DIR / "validation"),
            name=model_name,
            exist_ok=True,
        )

        comparison_rows.append({
            "Model": model_name,
            "Precision": metrics.box.mp,
            "Recall": metrics.box.mr,
            "mAP50": metrics.box.map50,
            "mAP50-95": metrics.box.map,
            "Inference ms/image": metrics.speed["inference"],
        })

    finally:
        del model
        gc.collect()

        if torch.cuda.is_available():
            torch.cuda.empty_cache()

comparison = pd.DataFrame(comparison_rows)

if not comparison.empty:
    comparison = comparison.round(4)
    display(comparison.sort_values("mAP50-95", ascending=False))

    comparison.to_csv(
        WORK_DIR / "model_comparison.csv",
        index=False,
    )
else:
    print("No saved model checkpoints were available to evaluate.")

Evaluating yolov8n...
Ultralytics 8.4.184 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
Model summary (fused): 73 layers, 3,132,707 parameters, 0 gradients, 8.6 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 670.3±240.6 MB/s, size: 16.9 KB)
val: Scanning /kaggle/working/amm_yolo/dataset_cardboard_v2/valid/labels.cache... 156 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 156/156 50.3Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 20/20 8.5it/s 2.4s
                   all        156        418      0.892      0.871      0.922      0.633
Speed: 1.7ms preprocess, 5.7ms inference, 0.0ms loss, 1.8ms postprocess per image
Results saved to /kaggle/working/amm_yolo/runs/validation/yolov8n
Evaluating yolov8s...
Ultralytics 8.4.184 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
Model summary (fused): 72 layers, 11,125,971 parameters, 0 gradients, 28.4 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 659.7±140.1 MB/s, size: 15.4 KB)
val: Scanning /kaggle/working/amm_yolo/dataset_cardboard_v2/valid/labels.cache... 156 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 156/156 46.7Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 20/20 6.3it/s 3.2s
                   all        156        418      0.894      0.847       0.91       0.64
Speed: 1.8ms preprocess, 10.7ms inference, 0.0ms loss, 1.4ms postprocess per image
Results saved to /kaggle/working/amm_yolo/runs/validation/yolov8s
Evaluating yolov8m...
Ultralytics 8.4.184 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
Model summary (fused): 92 layers, 25,840,339 parameters, 0 gradients, 78.7 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 585.0±198.7 MB/s, size: 13.7 KB)
val: Scanning /kaggle/working/amm_yolo/dataset_cardboard_v2/valid/labels.cache... 156 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 156/156 50.3Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 20/20 3.8it/s 5.3s
                   all        156        418      0.906      0.877      0.933      0.651
Speed: 1.6ms preprocess, 26.6ms inference, 0.0ms loss, 1.1ms postprocess per image
Results saved to /kaggle/working/amm_yolo/runs/validation/yolov8m

     Model  Precision  Recall   mAP50  mAP50-95  Inference ms/image
2  yolov8m     0.9061  0.8769  0.9334    0.6506             26.5717
1  yolov8s     0.8940  0.8469  0.9096    0.6401             10.6686
0  yolov8n     0.8922  0.8708  0.9217    0.6328              5.6922

# SAVING TRAINED MODELS RESULTS

In [12]:
ARTIFACT_ZIP = Path("/kaggle/working/amm_yolo_artifacts.zip")

with zipfile.ZipFile(
    ARTIFACT_ZIP,
    mode="w",
    compression=zipfile.ZIP_DEFLATED,
) as zip_file:

    # Include available final weights and training metadata.
    for path in MODEL_DIR.iterdir():
        if path.is_file():
            zip_file.write(path, arcname=path.name)

    comparison_csv = WORK_DIR / "model_comparison.csv"

    if comparison_csv.exists():
        zip_file.write(comparison_csv, arcname="model_comparison.csv")

print("Artifact archive created:", ARTIFACT_ZIP)
print("Archive size (MB):", round(ARTIFACT_ZIP.stat().st_size / 1024**2, 2))

display(FileLink(str(ARTIFACT_ZIP)))

Artifact archive created: /kaggle/working/amm_yolo_artifacts.zip
Archive size (MB): 142.43

/kaggle/working/amm_yolo_artifacts.zip

# Testing Evaluation

In [13]:
dataset_config_for_test = yaml.safe_load(Path(DATA_YAML).read_text(encoding="utf-8"))
if not dataset_config_for_test.get("test"):
    raise ValueError(
        "The dataset data.yaml does not define a 'test' split. "
        "A held-out test evaluation cannot run until that split is configured."
    )

testing_rows = []

for model_name in MODEL_CHECKPOINTS:
    weights = MODEL_DIR / f"{model_name}_best.pt"

    if not weights.is_file():
        raise FileNotFoundError(
            f"Required checkpoint for {model_name} was not found: {weights}. "
            "Run/fix CHECKPOINTS UPDATE before testing."
        )

    print(f"HELD-OUT TEST evaluation: {model_name}")
    model = YOLO(str(weights))

    try:
        metrics = model.val(
            data=str(DATA_YAML),
            split="test",
            imgsz=EVAL_IMGSZ,
            batch=EVAL_BATCH,
            device=EVAL_DEVICE,
            workers=2,
            plots=True,
            project=str(RUNS_DIR / "testing_evaluation"),
            name=model_name,
            exist_ok=True,
            verbose=True,
        )

        testing_rows.append({
            "Model": model_name,
            "Precision": float(metrics.box.mp),
            "Recall": float(metrics.box.mr),
            "mAP50": float(metrics.box.map50),
            "mAP50-95": float(metrics.box.map),
            "Inference ms/image": float(metrics.speed["inference"]),
        })

    finally:
        del model
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

testing_evaluation = pd.DataFrame(testing_rows)
if testing_evaluation.empty:
    raise RuntimeError("Held-out testing evaluation produced no results.")

testing_evaluation = testing_evaluation.round(4).sort_values(
    "mAP50-95", ascending=False
)
display(testing_evaluation)
testing_evaluation.to_csv(
    WORK_DIR / "testing_evaluation.csv", index=False
)
print("Held-out testing evaluation saved:", WORK_DIR / "testing_evaluation.csv")

# Combine the three same-format tables into one report-friendly CSV while preserving
# the separate CSV files for easier analysis.
combined_evaluation = pd.concat(
    [
        training_evaluation.assign(Split="train"),
        comparison.assign(Split="val"),
        testing_evaluation.assign(Split="test"),
    ],
    ignore_index=True,
)
combined_evaluation = combined_evaluation[
    ["Split", "Model", "Precision", "Recall", "mAP50", "mAP50-95", "Inference ms/image"]
]
combined_evaluation.to_csv(
    WORK_DIR / "train_val_test_evaluation.csv", index=False
)
print("Combined train/val/test results saved:", WORK_DIR / "train_val_test_evaluation.csv")

HELD-OUT TEST evaluation: yolov8n
Ultralytics 8.4.184 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
Model summary (fused): 73 layers, 3,132,707 parameters, 0 gradients, 8.6 GFLOPs
WARNING ⚠️ val: Slow image access detected (ping: 0.0±0.0 ms, read: 12.0±9.6 MB/s, size: 17.1 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips
val: Scanning /kaggle/working/amm_yolo/dataset_cardboard_v2/test/labels... 79 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 79/79 1.0Kit/s 0.1s
val: New cache created: /kaggle/working/amm_yolo/dataset_cardboard_v2/test/labels.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.9it/s 1.7s
                   all         79        185      0.906      0.838      0.924      0.653
Speed: 2.4ms preprocess, 6.0ms inference, 0.0ms loss, 4.4ms postprocess per image
Results saved to /kaggle/working/amm_yolo/runs/testing_evaluation/yolov8n
HELD-OUT TEST evaluation: yolov8s
Ultralytics 8.4.184 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
Model summary (fused): 72 layers, 11,125,971 parameters, 0 gradients, 28.4 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 722.1±162.2 MB/s, size: 20.4 KB)
val: Scanning /kaggle/working/amm_yolo/dataset_cardboard_v2/test/labels.cache... 79 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 79/79 25.5Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.1it/s 1.9s
                   all         79        185      0.936      0.865      0.927      0.652
Speed: 2.7ms preprocess, 12.5ms inference, 0.0ms loss, 2.2ms postprocess per image
Results saved to /kaggle/working/amm_yolo/runs/testing_evaluation/yolov8s
HELD-OUT TEST evaluation: yolov8m
Ultralytics 8.4.184 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
Model summary (fused): 92 layers, 25,840,339 parameters, 0 gradients, 78.7 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 581.1±275.2 MB/s, size: 15.4 KB)
val: Scanning /kaggle/working/amm_yolo/dataset_cardboard_v2/test/labels.cache... 79 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 79/79 33.1Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3it/s 3.0s
                   all         79        185      0.956      0.827      0.946      0.657
Speed: 2.7ms preprocess, 27.4ms inference, 0.0ms loss, 1.0ms postprocess per image
Results saved to /kaggle/working/amm_yolo/runs/testing_evaluation/yolov8m

     Model  Precision  Recall   mAP50  mAP50-95  Inference ms/image
2  yolov8m     0.9563  0.8272  0.9455    0.6568             27.4309
0  yolov8n     0.9065  0.8378  0.9238    0.6533              5.9782
1  yolov8s     0.9364  0.8649  0.9272    0.6521             12.4778

Held-out testing evaluation saved: /kaggle/working/amm_yolo/testing_evaluation.csv
Combined train/val/test results saved: /kaggle/working/amm_yolo/train_val_test_evaluation.csv

In [14]:
#!ls runs/detect